"""
schemas.py — Pydantic Request & Response Models
================================================
Defines structured schemas for the FastAPI REST API.
"""

from __future__ import annotations

from typing import Any
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Chat Schemas
# ---------------------------------------------------------------------------


class ChatRequest(BaseModel):
    """Payload for conversational question answering."""

    question: str = Field(
        ...,
        min_length=1,
        description="The natural language question to ask the AI.",
        examples=["Công ty ABC được thành lập khi nào?"],
    )
    session_id: str = Field(
        default="default",
        min_length=1,
        description="Session identifier for multi-turn conversational memory.",
        examples=["default", "user-123"],
    )


class DocumentSource(BaseModel):
    """Metadata and excerpt of a retrieved reference document."""

    source: str = Field(..., description="Origin of the chunk (file name, user_input, etc.)")
    doc_type: str | None = Field(default=None, description="Document type (pdf, docx, text)")
    page: int | str | None = Field(default=None, description="Page number if applicable")
    chunk_index: int | None = Field(default=None, description="Index of the chunk in document")
    content_snippet: str = Field(..., description="Excerpt of the retrieved context chunk")


class ChatResponse(BaseModel):
    """Response returned by the non-streaming chat endpoint."""

    session_id: str = Field(..., description="Active session ID")
    question: str = Field(..., description="The user's original question")
    answer: str = Field(..., description="Grounded response generated by Gemini")
    sources: list[DocumentSource] = Field(
        default_factory=list,
        description="List of relevant document chunks retrieved from pgvector",
    )


class SessionListResponse(BaseModel):
    """List of active in-memory session IDs."""

    active_sessions: list[str] = Field(..., description="All currently active session identifiers")


class SessionClearResponse(BaseModel):
    """Confirmation when a session's history is cleared."""

    session_id: str
    message: str


# ---------------------------------------------------------------------------
# Document Ingestion Schemas
# ---------------------------------------------------------------------------


class TextIngestRequest(BaseModel):
    """Payload for direct plain-text ingestion."""

    content: str = Field(
        ...,
        min_length=1,
        description="Raw text content to store into the knowledge base.",
        examples=["V-Act là một hệ thống đánh giá hoạt động dựa trên AI."],
    )


class IngestResponse(BaseModel):
    """Response returned after ingesting documents."""

    message: str = Field(..., description="Status message")
    doc_type: str = Field(..., description="Type of ingested document (pdf, docx, text)")
    source: str = Field(..., description="Source identifier or filename")
    chunks_ingested: int = Field(..., description="Number of chunks stored in pgvector")


class DocStatsResponse(BaseModel):
    """Statistics of stored documents in the vector store."""

    total_documents: int = Field(..., description="Total document chunks in pgvector table")
    table_name: str = Field(..., description="PostgreSQL table name")
    embedding_dimensions: int = Field(..., description="Dimensions of vector embeddings")


# ---------------------------------------------------------------------------
# System / Health Schemas
# ---------------------------------------------------------------------------


class HealthResponse(BaseModel):
    """Health check status and system configuration."""

    status: str = Field(..., description="Overall service status (healthy / degraded)")
    database: str = Field(..., description="PostgreSQL + pgvector connection status")
    llm_model: str = Field(..., description="Configured Gemini chat model")
    embedding_model: str = Field(..., description="Configured Gemini embedding model")
    total_documents: int = Field(..., description="Total chunks currently stored in vector DB")
